### ISSUE TITLE
bug: `wmill sync push` cannot bundle Svelte raw apps since 1.775.2 — `svelte.compile is not a function`

### ISSUE THREAD

**Issue by ClumsyAdmin** [windmill-labs/windmill#10621]
# Describe the bug

Since windmill-cli **1.775.2**, `wmill sync push` fails to bundle any Svelte raw app. It reproduces locally on macOS with the current CLI (1.783.0) on a minimal app, and in CI on `ubuntu-latest`.

Minimal local reproduction — a raw app whose only dependency is `svelte`, one `App.svelte`, one edited line:

```
$ wmill sync push --includes 'f/admin/test_app.raw_app/**'
CLI version: 1.783.0
Remote version: EE v1.782.0
remote (<workspace>) <- local: 1 changes to apply
~ raw_app f/admin/test_app.raw_app/App.svelte
...
Applying changes to files ...
found changes for 1 items with a total of 1 files to process
Loaded 1 runnables from backend folder
Generating fresh policy for app f/admin/test_app...
Creating raw app f/admin/test_app bundle...
📦 node_modules not found, running npm install...

added 20 packages, and audited 21 packages in 1s

✅ npm install completed
🔧 Svelte detected, adding svelte plugin...
📦 Building bundle...
✘ [ERROR] svelte.compile is not a function [plugin svelte]

    f/admin/test_app.raw_app/index.ts:3:16:
      3 │ import App from './App.svelte'
        ╵                 ~~~~~~~~~~~~~~

1 error
Build failed with 1 error:
f/admin/test_app.raw_app/index.ts:3:16: ERROR: [plugin: svelte] svelte.compile is not a function
/Users/…/lib/node_modules/windmill-cli/node_modules/esbuild/lib/main.js:1748
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
    at failureErrorWithLog (…/windmill-cli/node_modules/esbuild/lib/main.js:1748:15)
    …
Node.js v22.13.0
```

The whole app is:

```
test_app.raw_app/
├── App.svelte      (460 B)
├── backend/
├── index.css       (58 B)
├── index.ts        (177 B)
├── package.json    { "dependencies": { "svelte": "^5.56.8" } }
└── raw_app.yaml
```

Notes:

- It is not specific to one app. In CI the push aborts on the first raw app it reaches, and every Svelte raw app we have reproduces it.
- `wmill app dev` builds the same apps fine with the same CLI version installed, so only the `sync push` bundling path seems affected.
- The push dies with an unhandled esbuild error rather than a handled failure, which also leaves it ambiguous whether anything was partially applied remotely.

**Bisected to 1.775.1 → 1.775.2.** I installed each published version in that range and checked whether `esm/main.js` contains `requireFromApp.resolve("svelte/compiler")`:

| version | contains `requireFromApp.resolve("svelte/compiler")` |
|---|---|
| 1.775.1 | no |
| 1.775.2 | yes |
| 1.776.0 – 1.783.0 | yes |

1.775.1 is the last version that bundled our Svelte raw apps successfully in CI — it bundled two of them in one job. Every version from 1.775.2 onward, including the current latest 1.783.0, fails.

# To reproduce

1. Create a raw app whose `package.json` has a Svelte 5 dependency:

   ```json
   { "dependencies": { "svelte": "5.56.8" } }
   ```

   (also reproduced with `^5.56.8`, `5.45.2`, `5.46.1`)

2. `npm install -g windmill-cli@1.783.0`
3. `wmill sync push`
4. The bundle step fails with `svelte.compile is not a function`.

### Isolating it to the compiler load

This builds the same app twice with esbuild, changing **only** how the Svelte compiler module is obtained — same app, same `node_modules`, same esbuild, same plugin body:

```js
const APP = '/path/to/test_app.raw_app/';

// how the CLI loaded it up to 1.775.1: the ESM entry
const loadOld = () => import(pathToFileURL(path.join(APP, 'node_modules/svelte/src/compiler/index.js')).href);

// how the CLI loads it from 1.775.2 on
const loadNew = () => {
  const r = createRequire(path.join(path.resolve(APP), 'package.json'));
  return import(pathToFileURL(r.resolve('svelte/compiler')).href);
};

// ...then, in the esbuild onLoad handler for .svelte files:
const svelte = await load();
const { js } = svelte.compile(source, { filename: args.path });
```

Result:

```
(A) ESM entry            -> BUILD OK
(B) require.resolve      -> FAILED: [plugin: svelte] svelte.compile is not a function
```

To be precise about what this does and does not show: (A) is not literally 1.775.1's code — 1.775.1 did a bare `await import("svelte/compiler")` and I substituted "load the app's ESM compiler entry directly". So this isolates the failing step, but it is not a reproduction of the old version's exact resolution.

### Smaller still, without esbuild

Run from inside a directory that has `svelte` installed:

```js
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import path from 'node:path';

const appDir = process.cwd();
const bare = await import('svelte/compiler');
console.log('bare import    : typeof compile =', typeof bare.compile);

const requireFromApp = createRequire(path.join(path.resolve(appDir), 'package.json'));
const entry = requireFromApp.resolve('svelte/compiler');
const viaResolve = await import(pathToFileURL(entry).href);
console.log('require.resolve: ->', path.relative(appDir, entry));
console.log('               : namespace keys =', Object.keys(viaResolve).join(', '));
console.log('               : typeof compile =', typeof viaResolve.compile);
console.log('               : typeof default.compile =', typeof viaResolve.default?.compile);
```

Output (svelte 5.56.8), identical on Node 18.20.5 and Node 22.13.0:

```
bare import    : typeof compile = function
require.resolve: -> node_modules/svelte/compiler/index.js
               : namespace keys = default
               : typeof compile = undefined
               : typeof default.compile = function
```

I could not test Node 20.20.2 (our CI runner) directly, but 18 and 22 behave the same.

# Expected behavior

`wmill sync push` bundles Svelte raw apps, as it did on 1.775.1.

# What I suspect — I may be wrong about the mechanism

I have not read the change that introduced this, so please treat the following as a lead rather than a diagnosis.

1.775.2 appears to have introduced a `loadSvelteCompiler` helper in `esm/main.js`:

```js
async function loadSvelteCompiler(appDir) {
  try {
    const requireFromApp = createRequire(path.join(path.resolve(appDir), "package.json"));
    const entry = requireFromApp.resolve("svelte/compiler");
    return await import(pathToFileURL(entry).href);
  } catch {
    return await import("svelte/compiler");
  }
}
```

where 1.775.1 did it inline as `const svelte = await import("svelte/compiler")`.

Svelte 5 declares two entries for that subpath (`npm view svelte@5.56.8 exports`):

```json
"./compiler": {
  "types": "./types/index.d.ts",
  "default": "./src/compiler/index.js",
  "require": "./compiler/index.js"
}
```

`./src/compiler/index.js` is ESM and exports `compile` as a named export. `./compiler/index.js` is a minified UMD/CJS bundle that assigns onto `exports` from inside a wrapper:

```js
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports): ...
```

My guess is that `require.resolve` selects the `require` condition and therefore the CJS file, and that `import()`ing that file yields a namespace with only `default`, because Node's named-export detection cannot see the assignments through the UMD wrapper. `svelte.compile` is then undefined while `svelte.default.compile` is the real function — which is what both reproductions above show.

If that is roughly right, resolving through the `import`/`default` condition, or falling back to `mod.default?.compile` when the namespace has no `compile`, would presumably fix it. You will know better than I do whether the `require.resolve` step was added deliberately to solve some other resolution problem, in which case the fallback is probably the safer of the two.

**One thing I cannot explain**, which may mean my reading is wrong in some other way: the pre-1.775.2 bare `import("svelte/compiler")` is evaluated inside the CLI's own module, and the CLI is installed with `npm install -g`, so I would not have expected it to resolve the *app's* `svelte` at all. It demonstrably worked, so something about that resolution differs from my mental model.

I also have not verified that downgrading fixes it in place — the "1.775.1 is fine" half comes from our CI history, not from a downgrade-and-retry on the same machine.

There is no Svelte version to move to: the `./compiler` exports map has the same shape in 5.38.0, 5.45.2, 5.46.1, 5.50.0, 5.55.0, 5.56.0 and 5.56.8.

# Versions

- **windmill-cli**: reproduced on 1.782.0 (CI) and 1.783.0 (local, current latest); bisect points at 1.775.2 as the first affected; 1.775.1 last known good
- **Backend**: EE v1.782.0, self-hosted
- **Node**: 22.13.0 (macOS, local repro); 20.20.2 (GitHub Actions `ubuntu-latest`, `actions/setup-node@v4`); resolution behaviour also checked on 18.20.5
- **svelte**: 5.56.8 (also 5.45.2, 5.46.1)
- **OS**: macOS (darwin 25.5.0) and `ubuntu-latest`

The failing command in CI:

```yaml
- run: |
    npm install -g windmill-cli@1.782.0
    wmill sync push --yes --skip-variables --skip-secrets --skip-resources \
      --workspace "$WMILL_WORKSPACE" --token "$WMILL_TOKEN" --base-url "$WMILL_URL"
```
